import { style } from "@vanilla-extract/css";
import { vars } from "./theme.css";

export const layout = {
  shell: style({
    height: "100%",
    display: "grid",
    gridTemplateColumns: "70px 246px minmax(0, 1fr)",
    overflow: "hidden",
    "@media": { "(max-width: 760px)": { gridTemplateColumns: "56px minmax(0, 1fr)" } },
  }),
  rail: style({
    background: vars.color.rail,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 11,
    padding: "16px 8px",
    overflowY: "auto",
    "@media": { "(max-width: 760px)": { gridRow: "1 / 3", padding: "12px 4px" } },
  }),
  railButton: style({
    width: 46,
    height: 46,
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    border: 0,
    borderRadius: 15,
    background: vars.color.raised,
    color: vars.color.ink,
    fontWeight: 800,
    fontSize: 18,
    transition: "border-radius .18s, background .18s",
    ":hover": { borderRadius: 12, background: vars.color.accentStrong },
    "@media": { "(max-width: 760px)": { width: 42, height: 42 } },
  }),
  railSelected: style({ borderRadius: 12, background: vars.color.accentStrong }),
  railDivider: style({ height: 1, width: 32, background: vars.color.line, margin: "5px 0" }),
  sidebar: style({
    minHeight: 0,
    background: vars.color.sidebar,
    display: "flex",
    flexDirection: "column",
    borderRight: `1px solid ${vars.color.line}`,
    "@media": {
      "(max-width: 760px)": {
        gridColumn: 2,
        maxHeight: 210,
        borderBottom: `1px solid ${vars.color.line}`,
      },
    },
  }),
  sidebarHeader: style({
    padding: "22px 18px 14px",
    fontSize: 16,
    fontWeight: 750,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  }),
  sidebarScroll: style({ overflowY: "auto", padding: "0 8px 18px", minHeight: 0 }),
  sidebarItem: style({
    width: "100%",
    display: "block",
    textAlign: "left",
    padding: "9px 12px",
    border: 0,
    borderRadius: 7,
    background: "transparent",
    color: vars.color.muted,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    ":hover": { background: vars.color.raised, color: vars.color.ink },
  }),
  sidebarSelected: style({ background: vars.color.raised, color: vars.color.ink, fontWeight: 650 }),
  category: style({
    color: vars.color.muted,
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: 1,
    textTransform: "uppercase",
    margin: "23px 10px 7px",
  }),
  main: style({
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: vars.color.bg,
    "@media": { "(max-width: 760px)": { gridColumn: 2, minHeight: 0 } },
  }),
  top: style({
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 14,
    minHeight: 66,
    padding: "12px 26px",
    borderBottom: `1px solid ${vars.color.line}`,
    "@media": { "(max-width: 760px)": { padding: "10px 14px", flexWrap: "wrap" } },
  }),
  title: style({
    fontSize: 18,
    fontWeight: 780,
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  spacer: style({ flex: 1 }),
  content: style({
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    padding: "22px clamp(16px, 4vw, 48px)",
    scrollbarGutter: "stable",
    "@media": { "(max-width: 760px)": { padding: "16px 12px" } },
  }),
  narrowContent: style({ width: "min(100%, 940px)", margin: "0 auto" }),
  footer: style({
    color: vars.color.muted,
    fontSize: 11,
    padding: "12px 24px",
    borderTop: `1px solid ${vars.color.line}`,
  }),
};
